version: "3.8"
services:
  frontend: 
    build: ./frontend
    ports:
      - 80:80
      - 443:443
    image: xxfiestadeamonxx/loan-libary-frontend:firstImage
    volumes:
      - ./frontend/nginx/certbot/www:/var/www/certbot/:ro
      - ./frontend/nginx/certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./frontend/nginx/certbot/www/:/var/www/certbot/:rw
  backend: 
    build: ./backend
    image: xxfiestadeamonxx/loan-libary-backend:firstImage
    restart: always
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=car_share
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=car_share
    volumes:
      - "./backend/assets/scripts/CreateAutoverleih.sql:/docker-entrypoint-initdb.d/1.sql"
      - dbdata:/var/lib/mysql
volumes:
  dbdata: