version: "3.8"
services:
  frontend: 
    build: ./frontend
    ports:
      - 80:80
    image: xxfiestadeamonxx/loan-libary-frontend:firstImage
    depends_on:
      - backend
  backend: 
    build: ./backend
    image: xxfiestadeamonxx/loan-libary-backend:firstImage
    environment:
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=car_share
    depends_on:
      - database
    ports:
      - 8081:8081
  database:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=car_share
    ports:
      - 3306:3306
    


